# ----------- CONFIGURABLE START -----------
title:            "记录下那些有趣的珠子..."
description:      "Write something!"
url:              
signoff:          "FZ" # Your name
facebook_appid:   # APP ID for like button, remove from /_includes/share.html if unwanted.
google_analytics: # Set tracking, remove from /javascripts/basic.js if unwanted.
share:            false # Turn on twitter and facebook share buttons

links:
  - name:         zfq212_2018@163.com
    url:          #//
    external:     true
  - name:         My github 
    url:          https://github.com/zfq212git
    external:     true
  - name:         About me
    url:          https://www.linkedin.com/in/feiqizhang
    external:     true
# ------------ CONFIGURABLE END ------------

permalink:        /posts/:title
defaults:
  - values:
      layout: "default"

theme: jekyll-theme-architect
